[package]
name = "rust-iotdb-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iotdb-client-rs="0.3.6"
chrono="0.4.19"
prettytable-rs="0.8.0"
rand="0.8.5"
structopt = "0.3.25"
